//
//  TabbarInteractor.swift
//  citychat
//
//  Created by Levente Vig on 2019. 07. 12..
//  Copyright (c) 2019. CodeYard. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class TabbarInteractor {
}

// MARK: - Extensions -

extension TabbarInteractor: TabbarInteractorInterface {
}
