//
//  ProductInteractor.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 11. 01..
//  Copyright (c) 2020. gesben. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ProductInteractor {
    private var cartProvider: CartService = RestClient.shared
}

// MARK: - Extensions -

extension ProductInteractor: ProductInteractorInterface {
    func add(data: DressData, completion: @escaping CartLoaded) {
        cartProvider.add(data: data) { completion($0) }
    }
    
}
