//
//  ProductInterfaces.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 11. 01..
//  Copyright (c) 2020. gesben. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ProductWireframeInterface: WireframeInterface {
}

protocol ProductViewInterface: ViewInterface {
}

protocol ProductPresenterInterface: PresenterInterface {
    func getProduct() -> ProductModel
}

protocol ProductInteractorInterface: InteractorInterface {
}
