//
//  ProductInterfaces.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 11. 01..
//  Copyright (c) 2020. gesben. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ProductWireframeInterface: WireframeInterface {
    func goToCart()
}

protocol ProductViewInterface: ViewInterface {
    func stopAnimation(success: Bool)
}

protocol ProductPresenterInterface: PresenterInterface {
    func getProduct() -> ProductModel
    func addToCartTapped()
    func goToCart()
}

protocol ProductInteractorInterface: InteractorInterface {
    func add(data: DressData, completion: @escaping CartLoaded )
}
