//
//  ProductWireframe.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 11. 01..
//  Copyright (c) 2020. gesben. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ProductWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(product: ProductModel? = nil) {
        let moduleViewController = ProductViewController()
        super.init(viewController: moduleViewController)

        let interactor = ProductInteractor()
        let presenter = ProductPresenter(view: moduleViewController, interactor: interactor, wireframe: self, product: product)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ProductWireframe: ProductWireframeInterface {
}
