//
//  HomeInteractor.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 10. 14..
//  Copyright (c) 2020. GesBen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeInteractor {
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {
}
