//
//  SelectedCategoryInterfaces.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 10. 18..
//  Copyright (c) 2020. GesBen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SelectedCategoryWireframeInterface: WireframeInterface {
    func showSelectedProduct(product: ProductModel)
}

protocol SelectedCategoryViewInterface: ViewInterface {
    func reload()
}

protocol SelectedCategoryPresenterInterface: PresenterInterface {
    func getProductsCount() -> Int
    func getItem(_ row: Int) -> ProductModel
    func getItems() -> [ProductModel]
    func itemSelected(_ row: Int)
    func setImageToModel(row: Int, image: UIImage)
}

protocol SelectedCategoryInteractorInterface: InteractorInterface {
    func getDressesByCategory(category: Int ,completion: @escaping DressesLoaded)
}
