//
//  SelectedCategoryInteractor.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 10. 18..
//  Copyright (c) 2020. GesBen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SelectedCategoryInteractor {
}

// MARK: - Extensions -

extension SelectedCategoryInteractor: SelectedCategoryInteractorInterface {
    func getProducts(completion: @escaping ([ProductModel]) -> Void ) {
        var products = Array.init(repeating: ProductModel(title: "Lorem psum this is a verry long titler", price: 420, imageUrl: ""), count: 10)
        DispatchQueue.global().asyncAfter(deadline: .now() + 1) {
            completion(products)
        }
    }
}
