//
//  SelectedCategoryInteractor.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 10. 18..
//  Copyright (c) 2020. GesBen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SelectedCategoryInteractor {
    let dressProvider: DressService = RestClient.shared
}

// MARK: - Extensions -

extension SelectedCategoryInteractor: SelectedCategoryInteractorInterface {
    func getLatestDresses(limit: Int, completion: @escaping DressesLoaded) {
        dressProvider.getLatestDresses(limit: limit) { completion($0) }
    }
    
    func getDressesByCategory(category: Int, completion: @escaping DressesLoaded) {
        dressProvider.getDressesByCategory(category: category) { completion($0) }
    }
    
}
