//
//  ProfileInterfaces.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 11. 07..
//  Copyright (c) 2020. gesben. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ProfileWireframeInterface: WireframeInterface {
}

protocol ProfileViewInterface: ViewInterface {
    func bind(user: User)
    func changeTextFieldState(state: TextFieldState, tag: Int)
}

protocol ProfilePresenterInterface: PresenterInterface {
    func saveButtonTapped()
    func textFieldChanged(text: String, tag: Int)
}

protocol ProfileInteractorInterface: InteractorInterface {
    func createProfile(data: User, completion: @escaping  ProfileLoaded)
    func getProfile(profileId: Int, completion: @escaping  ProfileLoaded)
    func getProfileByEmail(email: String, completion: @escaping  ProfileLoaded)
    func updateProfile(data: User, completion: @escaping  ProfileLoaded)
}
