//
//  SearchWireframe.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 10. 17..
//  Copyright (c) 2020. GesBen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SearchWireframe: BaseWireframe {

    weak var tabbarProtocol: CustomTabbarProtocol?
    
    // MARK: - Private properties -
    
    // MARK: - Module setup -

    init(tabbarProtocol: CustomTabbarProtocol? = nil) {
        let moduleViewController = SearchViewController()
        super.init(viewController: moduleViewController)
        self.tabbarProtocol = tabbarProtocol
        let interactor = SearchInteractor()
        let presenter = SearchPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SearchWireframe: SearchWireframeInterface {
    func showSelectedCategory(category: CategoryModel) {
        let wireframe = SelectedCategoryWireframe(category: category)
        wireframe.tabbarProtocol = self.tabbarProtocol
        navigationController?.pushWireframe(wireframe)
    }
}
