//
//  SearchInterfaces.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 10. 17..
//  Copyright (c) 2020. GesBen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SearchWireframeInterface: WireframeInterface {
    func showSelectedCategory()
}

protocol SearchViewInterface: ViewInterface {
    func reload()
}

protocol SearchPresenterInterface: PresenterInterface {
    func getSearchCount() -> Int
    func getItem(_ row: Int) -> CategoryModel
    func getItems() -> [CategoryModel]
    func itemSelected(_ row: Int)
}

protocol SearchInteractorInterface: InteractorInterface {
    func getCategories(completion: @escaping CategoryLoaded)
}
