//
//  SearchInterfaces.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 10. 17..
//  Copyright (c) 2020. GesBen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SearchWireframeInterface: WireframeInterface {
}

protocol SearchViewInterface: ViewInterface {
    func reload()
}

protocol SearchPresenterInterface: PresenterInterface {
    func getSearchCount() -> Int
    func getItem(_ row: Int) -> SearchCellModel
}

protocol SearchInteractorInterface: InteractorInterface {
    func getSearchCells(completion: @escaping ([SearchCellModel]) -> Void )
}
