//
//  SearchInteractor.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 10. 17..
//  Copyright (c) 2020. GesBen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SearchInteractor {
}

// MARK: - Extensions -

extension SearchInteractor: SearchInteractorInterface {
    func getSearchCells(completion: @escaping ([SearchCellModel]) -> Void ) {
        var searchCells = Dbs.shared.loadCategories()
        DispatchQueue.global().asyncAfter(deadline: .now() + 1) {
            completion(searchCells)
        }
    }
}
