//
//  CartInterfaces.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 11. 07..
//  Copyright (c) 2020. gesben. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CartWireframeInterface: WireframeInterface {
}

protocol CartViewInterface: ViewInterface {
    func reload()
    func removeProduct(row: Int)
}

protocol CartPresenterInterface: PresenterInterface {
    func getProductsCount() -> Int
    func getItem(row: Int) -> ProductModel
    func removeProduct(row: Int)
    func orderButtonTapped()
}

protocol CartInteractorInterface: InteractorInterface {
    func getProducts(customerId: Int, completion: @escaping CartLoaded )
    func removeProduct(orderId: Int, completion: @escaping CartLoaded )
    func updateCart(customerId: Int, completion: @escaping CartUpdated)
}
