//
//  CartInterfaces.swift
//  Webshop
//
//  Created by Geszti Bence on 2020. 11. 07..
//  Copyright (c) 2020. gesben. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CartWireframeInterface: WireframeInterface {
}

protocol CartViewInterface: ViewInterface {
}

protocol CartPresenterInterface: PresenterInterface {
}

protocol CartInteractorInterface: InteractorInterface {
}
